spring.application.name=user-request-sb

chunkSize=10
pageSize = 10

# Habilita o console web do H2 (acessível em /h2-console)
spring.h2.console.enabled=true

# Define o caminho do console
spring.h2.console.path=/h2-console

# Configura a URL do banco (memória) e o driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
